# Site
repository: kurtnheiss/kurtnheiss.io
favicon: images/favicon.ico

# Personal info
name: Kurt Heiss
title: Project Management/Content Development
email: kurtnheiss@gmail.com
website: www.github.com/kurtnheiss/kurtnheiss.io

# Social links
twitter_username: kurtnheiss
github_username:  kurtnheiss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: werewf
linkedin_username: kurtnheiss
# pinterest_username: jekyll
youtube_username: kurtnheiss
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kurt Heiss and I'm a Project Manager/Content Developer.
  
  I am most skilled in <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:
   - Surfing
   - Swimming
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
