# Site
repository: kurtnheiss/kurtnheiss.io
favicon: images/favicon.ico

# Personal info
name: Kurt Heiss
# title: Project Management/Content Development
email: kurtnheiss@gmail.com
## website: www.github.com/kurtnheiss/kurtnheiss.io

# Social links
twitter_username: kurtnheiss
github_username:  kurtnheiss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: werewf
linkedin_username: kurtnheiss
# pinterest_username: jekyll
youtube_username: kurtnheiss
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kurt 
  
  Content development and project management, currently based in San Jose via San Francisco, Seattle, and 
  Los Angeles. Alumnus of Santa Clara University and the University of Washington.

  Intrigued by strategy, organization, design, writing, art, vegetarian cooking, classical and metal music, IDM, and thought provoking conversation.

  Extensive and varied experience working at both established Silicon Valley tech giants as well as startups.
  
  Currently at 8x8 (a cloud all in suite of cloud commmunications solutions) helping develop their public API program.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In my free time, I like to learn new skills and exercise. 
  
  Right now I am taking front-end web developer coursework through [Free Code Camp](https://www.freecodecamp.org/kurtnheiss).
  
  Some of my other interests and hobbies are:
  
   - Surfing
   - Swimming 
   - Hiking
   - Writing screenplays
   - Clay and papier mache sculptors
   - Trying different techniques on the guitar and bass
   - Returning to the cello
   - Learning German
   - [Reading](https://www.goodreads.com/user/show/5016817-kurt-heiss)
   - Vegetarian cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
